### ISSUE TITLE
Android crash on App close

### ISSUE THREAD

**Issue by aleksei-z** [builttoroam/multiple_screens#20]
When App is closed it immediately crashes with RuntimeException "Unable to destroy activity" because of uninitialized methodChannel and eventChannel in MultipleScreensPlugin.kt.

D/AndroidRuntime(24552): Shutting down VM
E/AndroidRuntime(24552): FATAL EXCEPTION: main
E/AndroidRuntime(24552): Process: com.builttoroam.multiple_screens_example, PID: 24552
E/AndroidRuntime(24552): java.lang.RuntimeException: Unable to destroy activity {com.builttoroam.multiple_screens_example/com.builttoroam.multiple_screens_example.MainActivity}: kotlin.UninitializedPropertyAccessException: lateinit property methodChannel has not been initialized
E/AndroidRuntime(24552): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4946)
E/AndroidRuntime(24552): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4975)
E/AndroidRuntime(24552): 	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
E/AndroidRuntime(24552): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
E/AndroidRuntime(24552): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
E/AndroidRuntime(24552): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2021)
E/AndroidRuntime(24552): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(24552): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(24552): 	at android.app.ActivityThread.main(ActivityThread.java:7361)
E/AndroidRuntime(24552): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(24552): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(24552): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
E/AndroidRuntime(24552): Caused by: kotlin.UninitializedPropertyAccessException: lateinit property methodChannel has not been initialized
E/AndroidRuntime(24552): 	at com.builttoroam.multiple_screens.MultipleScreensPlugin.onDetachedFromEngine(MultipleScreensPlugin.kt:153)
E/AndroidRuntime(24552): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.remove(FlutterEnginePluginRegistry.java:252)
E/AndroidRuntime(24552): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.remove(FlutterEnginePluginRegistry.java:260)
E/AndroidRuntime(24552): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.removeAll(FlutterEnginePluginRegistry.java:268)
E/AndroidRuntime(24552): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.destroy(FlutterEnginePluginRegistry.java:112)
E/AndroidRuntime(24552): 	at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:365)
E/AndroidRuntime(24552): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:528)
E/AndroidRuntime(24552): 	at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:577)
E/AndroidRuntime(24552): 	at android.app.Activity.performDestroy(Activity.java:8071)
E/AndroidRuntime(24552): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1341)
E/AndroidRuntime(24552): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4931)
E/AndroidRuntime(24552): 	... 11 more

**Comment by aleksei-z** [comment]
Pull request created: #19
